#!/bin/bash
# Usage: script/ci [setup]
# Run the test suite on a Codeship build machine.
#set -e

bundle exec rake sleep db:create db:migrate

if [ "$1" == "spec" ]; then
    time bundle exec rspec
elif [ "$1" == "plugin" ]; then
    time bundle exec rake plugin:spec
elif [ "$1" == "qunit" ]; then
    time bundle exec rake qunit:test
fi
